### ISSUE TITLE
problems with config stuff  v.02 vs v.03

### ISSUE THREAD

**Issue by pnealgit** [beyretb/AnimalAI-Olympics#11]
The following code used to work (more or less) on v. 02. but not on v .03

I get an error :

python3 testMovement.py
Traceback (most recent call last):
  File "testMovement.py", line 2, in <module>
    from animalai.envs.ArenaConfig import ArenaConfig
ModuleNotFoundError: No module named 'animalai.envs.ArenaConfig'

When I change the line to:

from animalai.envs.arena_config import ArenaConfig

Lower case arena_config, things start to run but then I get:

CrashReporter: initialized
Mono path[0] = '/Users/pneal/aao/may26/env/AnimalAI.app/Contents/Resources/Data/Managed'
Mono config path = '/Users/pneal/aao/may26/env/AnimalAI.app/Contents/MonoBleedingEdge/etc'
INFO:mlagents.envs:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of Training Brains : 1
Traceback (most recent call last):
  File "testMovement.py", line 16, in <module>
    env.reset(config=arena_config_in, train_mode=True)
TypeError: reset() got an unexpected keyword argument 'config'

When I change the reset line to: 

env.reset(train_mode=True)

then I don't get the "justFood.yaml" environment, I get the huge default 
environment with lots of obstacles, etc.

Best regards,
Phil Neal

+++++++++++++++++++++++cut here for original code ++++++++++++++++=
from animalai.envs.environment import UnityEnvironment
from animalai.envs.ArenaConfig import ArenaConfig
import matplotlib.pyplot as plt

env= UnityEnvironment(
    file_name='env/AnimalAI',   # Path to the environment
    worker_id=6,                # Unique ID for running the environment (used for connection)
    seed=0,                     # The random seed
    docker_training=False,      # Whether or not you are training inside a docker
    no_graphics=False,          # Always set to False
    n_arenas=1,                 # Number of arenas in your environment
    play=True                  # Set to False for training
)

arena_config_in = ArenaConfig('configs/justFood.yaml')
env.reset(config=arena_config_in, train_mode=True)

#plt.ion()

def step(action):
    info = env.step(action)
    b1 = info['Learner']
    img = b1.visual_observations
    plt.imshow(img[0][0])
    plt.close()

**Comment by beyretb** [comment]
Hello,

``config`` has been remained ``arenas_configurations_input``, it works the same way as before. I will highlight this kind of changes in release notes in the future.

Benjamin

**Comment by pnealgit** [comment]
Hi Benjamin,
Thank you for all the work you have been doing on the AnimalAi environment.

A slight glitch:

In version 03

from animalai.envs.arena_config import ArenaConfig


worked ok.

But now , in version 04, it doesn't work and upon checking I have to use:

from animalai.envs.ArenaConfig import ArenaConfig



Should I be sending email to you directly about these
things or should I put them in the github 'issues'
section ?

Best regards,
Phil Neal

**Comment by beyretb** [comment]
Hi Phil,

You can leave questions here, it can always be helpful to others!

Regarding your issue it looks like you're not running v0.4 as `animal.envs.arena_config` is correct and works fine. Have a look at the three templates we're providing (`visualizeArena.py`, `visualizeLightsOff.py` and `train.py`), you'll find all syntax and dependencies needed.

Did you try a fresh install in a separate folder and virtual environment?

**Comment by beyretb** [comment]
As @krisives mentioned, you also need to make sure that you update both the environment (by downloading the executable file [here](https://github.com/beyretb/AnimalAI-Olympics#requirements), **as well as** the codebase by pulling the code from the repo.

This should be the update process for every release in the future, I will mention it in the documentation as well.

**Comment by pnealgit** [comment]
Hi Benjamin,
Yep. I did a complete re-install and now it all works. Yay !!!
Sorry to worry you
Phil


MAC

macOS Mojave

version 10.14.5



UNITY

May 29 loading unity 2019.1.4f1


MLAGENTS

pip3 show  mlagents

Name: mlagents

Version: 0.8.1


PYTHON

Python 3.6.6


AnimalAI.app -- env_mac_v0.4.zip

**Comment by beyretb** [comment]
glad it worked! I'll close the issue as it's solved
