### ISSUE TITLE
problem with config going from v 03 to v 04

### ISSUE THREAD

**Issue by pnealgit** [beyretb/AnimalAI-Olympics#13]
Hi,

I just upgraded to version 04 from 03.
I get this error message under v04:

   "env_info = env.reset(arenas_configurations_input=arena_config_in,train_mode=train_mode)[default_brain]
TypeError: reset() got an unexpected keyword argument 'arenas_configurations_input'"

env.reset works in v 04 when I use:

env_info = env.reset(config=arena_config_in,train_mode=train_mode)[default_brain]

( 'config 'as the keyword vs 'arenas_configurations_input')

Best regards 8-)

**Comment by beyretb** [comment]
Hi Phil,

See my answer on your other post [here](https://github.com/beyretb/AnimalAI-Olympics/issues/11#issuecomment-496833622), it looks like you're still on an older version of the environment as `arenas_configurations_input` is definitely the correct variable name.

I will close this issue as I think these are linked, please reopen it if you still face the issue after a fresh install.

**Comment by krisives** [comment]
Is it possible he has upgraded the Python code to 0.4 but not the Unity executable?

**Comment by beyretb** [comment]
Right, I didn't think about this one! It might even be the other way around (downloaded the new exec but didn't pull the code). I'll reply on the other issue to make sure everything is updated.

Thanks a lot for pointing it out
