### ISSUE TITLE
v 04 env.step returns only zeros for visual observations

### ISSUE THREAD

**Issue by pnealgit** [beyretb/AnimalAI-Olympics#14]
Hi,

With v 04 the python program below returns visual observations of all zeros
after the env.step call.  (with adjustments for the config yaml)

It returns visual_observations full of floats (correct) under v 03.

--------------------------------cut here for code----------------------------
from animalai.envs import UnityEnvironment
from animalai.envs.exception import UnityEnvironmentException
from animalai.envs.ArenaConfig import ArenaConfig
import sys

arena_config_in = ArenaConfig('configs/obstacles.yaml')
env_name = 'env/AnimalAI'
train_mode = True
env = UnityEnvironment(file_name=env_name)

default_brain = env.brain_names[0]
brain = env.brains[default_brain]
 
# Reset the environment
env_info = env.reset(config =arena_config_in, train_mode=train_mode)[default_brain]

action = [[0,0]]
env_info = env.step(action)[default_brain]
print("VISUAL OBS: ",env_info.visual_observations)
input("HIT ME: ")
env.close()

**Comment by beyretb** [comment]
Hi Phil,

Again I think this has to do with the same issue (see [here](https://github.com/beyretb/AnimalAI-Olympics/issues/11#issuecomment-496833622)). After a fresh install and modifying your code as follows (I just changed the import for `arena_config` and the `env.reset(arenas_configurations_input)`):

```
from animalai.envs import UnityEnvironment
from animalai.envs.arena_config import ArenaConfig

arena_config_in = ArenaConfig('configs/obstacles.yaml')
env_name = 'env/AnimalAI'
train_mode = True
env = UnityEnvironment(file_name=env_name)

default_brain = env.brain_names[0]
brain = env.brains[default_brain]

env_info = env.reset(arenas_configurations_input=arena_config_in, train_mode=train_mode)[default_brain]

action = [[0,0]]
env_info = env.step(action)[default_brain]
print("VISUAL OBS: ",env_info.visual_observations)
input("HIT ME: ")
env.close()
```

I obtain:

```
VISUAL OBS:  [array([[[[0.19215686, 0.30196078, 0.4745098 ],
         [0.19215686, 0.30196078, 0.4745098 ],
         [0.19215686, 0.30196078, 0.4745098 ],
         ...,
         [0.44705882, 0.37254902, 0.29019608],
         [0.43137255, 0.36078431, 0.2745098 ],
         [0.42745098, 0.35686275, 0.26666667]],

        [[0.19215686, 0.30196078, 0.4745098 ],
         [0.19215686, 0.30196078, 0.4745098 ],
         [0.19215686, 0.30196078, 0.4745098 ],
         ...,
         [0.43137255, 0.35686275, 0.26666667],
         [0.44705882, 0.36862745, 0.2745098 ],
         [0.43529412, 0.36470588, 0.26666667]],

        [[0.19215686, 0.30196078, 0.4745098 ],
         [0.19215686, 0.30196078, 0.4745098 ],
         [0.19215686, 0.30196078, 0.4745098 ],
         ...,
```

I will close this issue too, please reopen if you still face this problem after a fresh install.

**Comment by pnealgit** [comment]
Hi Ben,
Thank you for all your work and your quick
responses. I have a new problem/how-to-question.

So I have my  python program/"agent" running.
It seems to do ok. But it takes about 7 minutes
to train between "justFood.yaml" episodes.

I do not use tensorflow, so far just python.
Some feature engineering is done with OpenCV and
the results are manipulated and jammed into
an off-brand numpy neural network.

So, I see 2 alternatives:

1. Drink the Kool-aid and go to Tensorflow with
    hefty use of tf.py_func which may or may not
    speed things up

2. Use some sort of tcp/ip socket connection
     that communicates with the "agent" re-written
     in C++ maybe out on different processors

Soooo, I was poking around in the V 05 animalai
directories and found some code that seems
to do what I want:
 ./animalai/animalai/envs/socket_communicator.py

How do I use this within the context of the arena ?
Is it a "brain" ? An "external brain" ?

Is there an example program ?

Best regards,
Phil

**Comment by beyretb** [comment]
Hi Phil,

The speed at which you will be able to run the environment and train is very dependent on your hardware.
Also, you need to differentiate two things that can take more or less time:
- Taking a single step in the environment
- Training of your algorithm

If I understand your question correctly, your point "1." is regarding training (which library to use to train the agent), and point "2." is related to taking steps in the environment.

Regarding training, you are completely free to implement whichever technique you want using any library you prefer (OpenCV in your case). However, this should not be linked to the performance of the environment and we cannot really help on that side as this part of the challenge is what is required from the participants.

On the environment side, we have optimised the executable as much as possible to prevent the call to `env.step()` to be a bottleneck. To test for this, you can try to run a few thousand steps in the environment alone (without any training) and see how long it takes, put this code in your example folder and run it:

```
from animalai.envs import UnityEnvironment
from animalai.envs.arena_config import ArenaConfig
import numpy as np
import time

env = UnityEnvironment(
    n_arenas=1,
    file_name='../env/AnimalAI',
    worker_id=1,
    seed=0,
    docker_training=False,
    play=False
)
env.reset(arenas_configurations=ArenaConfig('configs/justFood.yaml'))

N = 10000
before = time.time()
for _ in range(N):
    env.step(np.random.randint(0, 3, size=2))
after = time.time()

print('Steps per second: {0}'.format(N / (after - before)))
env.close()
```
on Linux with an i7 and GTX730 I get to 320 steps per second.

Finally, if you wish to re-implement your own communicator and training interface you can do so, but keep in mind that at the time of submission we will expect an agent that implements `agent.py` (**the syntax of which will most likely change by the launch date**).
If you still want to follow this route we will not provide help in any other language than python. I can only encourage you to read and debug the code in `animalai/envs` and familiarise yourself with protobuf which is the protocol used to communicate.

Hope this helps,
Benjamin

**Comment by pnealgit** [comment]
Hi Benjamin,
Thank you for your response.
The env.step function is definitely not the problem.
The big time consumer is the pre-processing.

I will focus on making everything work inside agent.py

Thanks again,
Phillip
