### ISSUE TITLE
v 05 config variable name

### ISSUE THREAD

**Issue by pnealgit** [beyretb/AnimalAI-Olympics#17]
Hi,
I just built a new v 05 following the directions 

However, I have this problem:

Under v 04 this line worked:

env_info = env.reset(arenas_configurations_input=arena_config_in,train_mode=train_mode)[default_brain]

But under v 05 I have to change it:

env_info = env.reset(arenas_configurations=arena_config_in,train_mode=train_mode)[default_brain]

I had to lop off the "_input"

It could be me with a version mis-match. I dunno.

**Comment by beyretb** [comment]
Hi, you are correct this has been changed for consistency. It is highlighted in the documentation and the source code which I recommend to look at between releases as we are still on dev versions
