### ISSUE TITLE
BadGoal returns positive reward

### ISSUE THREAD

**Issue by dan9thsense** [beyretb/AnimalAI-Olympics#22]
I have the environment up and running well.  However, when I run into a "BadGoal" it returns a positive reward, just like a "GoodGoal" (0.5 to 5 depending on the size).  It shows up with the correct color (red) in the arena and "GoodGoal" shows up green, as expected.

**Comment by beyretb** [comment]
Hello,

thanks for reporting this bug, I've fixed it and will include this as part of v0.6 which should be released in 2 days.

Ben

**Comment by mdcrosby** [comment]
Should be fixed in the latest version.

**Comment by dan9thsense** [comment]
Tested and found fixed in version 0.6
