### ISSUE TITLE
Could not install animalai-train

### ISSUE THREAD

**Issue by shanejohnpaul** [beyretb/AnimalAI-Olympics#28]
It seems to require tensorflow==1.12.2, but it is not available.
Could you help me with this?

` ERROR: Could not find a version that satisfies the requirement tensorflow==1.12.2 (from animalai-train) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
ERROR: No matching distribution found for tensorflow==1.12.2 (from animalai-train)`

**Comment by shanejohnpaul** [comment]
I went inside setup.py and requires.txt and changed
`tensorflow==1.12.1`
to
`tensorflow>=1.12.1`
and it got installed.

**Comment by beyretb** [comment]
Hello,

What command did you run to install `animalai-train` ?

It indeed requires tensorflow 1.12.2 which is a valid version ([see here](https://github.com/tensorflow/tensorflow/releases/tag/v1.12.2)). You also talk about version 1.12.1 which does not exist, so I m a bit confused as to which install files/repository you're using.

You can either run `pip install animalai-train`, or alternatively clone (or pull if you already cloned) this repository and then go to `examples/animalai-train/` and run `pip install .` from here.

Let me know if you still face this issue.

**Comment by shanejohnpaul** [comment]
Sorry, I only meant 1.12.2 version.
I tried `pip install animalai-train`, that's when it said it requires tf1.12.2 and gave the above error. So I modified the file in the `examples/animalai-train` and installed it using `pip install -e .` and it worked.

Are the later versions of tensorflow not supported?

**Comment by beyretb** [comment]
We provide the `animalai-train` package as an example/starting point for training agents, you can use whichever library you prefer. The code provided relies on tf 1.12.2, it hasn't been tested with 1.12.3 but it should work too. The evaluation platform will be running CUDA 10 which is why we chose this version, but as long as your package is compatible you should be good.

Both commands work just fine for me, are you running python 3.6?

**Comment by shanejohnpaul** [comment]
I'm actually running python 3.7. 😅

**Comment by beyretb** [comment]
Unfortunately we only support 3.6 for now. If you're not already doing so, you can work with [conda environments](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) to have both versions running without conflicts.

**Comment by shanejohnpaul** [comment]
Now, after installing python3.6, everything's working fine.
Thanks!
