### ISSUE TITLE
Observations and actions: Z component of speed

### ISSUE THREAD

**Issue by pauljurczak** [beyretb/AnimalAI-Olympics#3]
The speed of the agent is 3-dimensional but the actions are 2-dimensional only. Does it imply that Z component of speed is always zero and the agent location is restricted to XY plane?

**Comment by beyretb** [comment]
Hello,

The agent can move in 3 dimensions as it can climb on ramps.

Also the vertical axis is the Y one, have a look at the [list of objects documentation](documentation/definitionsOfObjects.md) to see what the referential looks like and how objects are oriented.

**Comment by pnealgit** [comment]
The max size of my discrete action vector is 2. 
When I add a third, I get this message:
"animalai.envs.exception.UnityActionException: There was a mismatch between the provided action and the environment's expectation: The brain Learner expected 2 discrete action(s), but was provided: [0.0, 1.0, 0.0]"

Also, in the "actions" documentation, there is no text about zooming in or out (flying,looking around)
just left/right , forward/reverse

When I examine the brain and env objects, I do not see any attribute for speed ?
