### ISSUE TITLE
[Request] Cloud quickstart guide

### ISSUE THREAD

**Issue by RedTachyon** [beyretb/AnimalAI-Olympics#30]
Something I feel would be very useful especially to allow participation for users who do not have access to huge computing clusters (since I feel it shouldn't be the point that whoever has the most compute wins) and aren't necessarily used to setting them up, since it seems like my measly CPU wouldn't be quite enough to train any models here.

I'm actually trying to figure that out right now with Docker, but maybe a premade container with instructions how to deploy it on GCP would be very helpful

**Comment by beyretb** [comment]
Hello,

We will release documentation for exactly that this week. It will be part of a "submission documentation" covering creating a docker and using AWS p2 instances (GPU enabled), which will be used to evaluate your submissions. This docker will work for training as well after adding your own libraries.

In the meantime, I've added a [dockerfile for you](https://github.com/beyretb/AnimalAI-Olympics/blob/submission/submission/Dockerfile). To use CUDA capabilities on the docker you ll need to use [this](https://marmelab.com/blog/2018/03/21/using-nvidia-gpu-within-docker-container.html#installing-nvidia-docker) (comes pre-installed on most compute instances). Finally, when creating your environment select `docker_training=True` and you're good to go.

Keep in mind we're still working on the submission pipeline and this Dockerfile might be a bit different next week.

**Comment by vakker** [comment]
@beyretb could you give us an update on the cloud docs?
Also, the Dockerfile link seems to be broken.
Thanks

**Comment by beyretb** [comment]
[There you go!](https://github.com/beyretb/AnimalAI-Olympics/blob/master/documentation/cloudTraining.md)

I'll leave this thread open a bit, in case something is missing and/or not clear.

**Comment by beyretb** [comment]
closing this as there seem to be no questions
