### ISSUE TITLE
turning the wrong way?

### ISSUE THREAD

**Issue by dan9thsense** [beyretb/AnimalAI-Olympics#35]
I must have misunderstood something.  When I send an action to turn right [0.0, 2.0], the image returned looks like the agent has turned to the left.  vice versa with an action to turn left [0.0, 1.0], the agent appears to be turning to the right.  Forward and back appear correct.

In standalone mode, WASD works correctly.

Anyone else seeing this?

**Comment by beyretb** [comment]
You are correct: [0,1] turns right and [0,2] turns left, while [1,0] is forward and [2,0] is backward.

I don't think we mentioned which is which, hence the confusion, we'll clarify that in the documentation.

**Comment by dan9thsense** [comment]
[Here](https://github.com/beyretb/AnimalAI-Olympics/blob/master/documentation/training.md) is where I got the idea that [0,1] turns left and [0,2] turns right (and I think there was a version of the code that did that).  It says:

Actions: the agent can move forward/backward and rotate left/right, just like in play mode. The actions are discrete and of dimension 2, each component can take 3 values ((nothing, forward, backward) and (nothing, left,right)).

**Comment by beyretb** [comment]
OK i see where the confusion is coming from, the order wasn't meant to represent which action does what, we'll clarify that with the next release (Monday)
