### ISSUE TITLE
movement model

### ISSUE THREAD

**Issue by dan9thsense** [beyretb/AnimalAI-Olympics#37]
There is something odd about the movement model.  It does not apply a constant force with each forward step-- the velocity change with each forward action diminishes as the velocity increases. 
 Can you provide more insight into this aspect of the movement model?

Also, establishing a high velocity moving forward and then doing a series of turns without a forward or back component would be expected to yield a negative z velocity once the turn exceeds 90 degrees, but it does not.

See these data:
enter next action: 0
sending next action:  [0.0, 0.0]
Velocity observed:  x = 0.00, z = 0.00

We are stopped in one corner of the arena, facing the opposite corner.
Now we move forward:

enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = 0.00, z = 2.44
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = 0.00, z = 4.60

At first, our velocity increases by about 2.4 m/s with each push

enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = 0.00, z = 6.51
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = 0.00, z = 8.20
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = 0.00, z = 9.70
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 11.02
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 12.19
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 13.23
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 14.14
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 14.95
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 15.67
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 16.30
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 16.87
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 17.36
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 17.80
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 18.19
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 18.53
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 18.84
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 19.11
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 19.35
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 19.56
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 19.74
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = -0.00, z = 19.91
enter next action: 1
sending next action:  [1.0, 0.0]
Velocity observed:  x = 0.00, z = 20.05

The final forward push only increases our velocity by 0.14 m/sec
We are moving fast toward the opposite corner of the arena.  Now we will turn in place, with no additional forward or backward inputs.

enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 1.82, z = 17.32

The x velocity increases, as expected, since we are now moving in a different direction than we are facing.

enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 3.14, z = 14.75
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 4.02, z = 12.38
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 4.55, z = 10.23
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 4.79, z = 8.29
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 4.79, z = 6.59
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 4.61, z = 5.12

Friction is slowing us down, as expected.

enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 4.28, z = 3.86
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 3.86, z = 2.81
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 3.38, z = 1.95
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 2.85, z = 1.27

At this point we have turned more than 90 degrees, so we should have a negative z velocity, but it is still positive

enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 2.32, z = 0.75
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 1.79, z = 0.38
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 1.29, z = 0.14

Even though we have turned about 140 degrees, our z velocity is still positive.

enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 0.82, z = -0.00

At last z velocity is 0.  This should have happened when we were turned 90 degrees, but at this point we have turned about 150 degrees.

enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 0.40, z = -0.04
enter next action: 3
sending next action:  [0.0, 2.0]
Velocity observed:  x = 0.00, z = 0.00

Eventually, friction makes us stop.

**Comment by mdcrosby** [comment]
Hi, 

When we test this on the released version we get that the agent turns roughly 90 degrees before stopping which is consistent with your recorded velocity values, but not your observation that the agent has turned ~140 degrees. When we artificially increase the rotation speed (to ensure that the agent has turned >90 degrees before stopping) we get negative z values as expected. 

Could you let us know how you get the 140 degrees observation? We get ~90 whether trying this by hand or using the sequence of actions from your comment.

**Comment by dan9thsense** [comment]
You are right.  Earlier I had found that each turn input caused a 10 degree rotation and, trying now, I see that it only puts in a 6 degree rotation.  I was basing the result on a 10 degree rotation per input.

Redoing the experiment showed that the z speed does go to zero when the turn gets to 90 degrees and then goes negative, as expected.  

How about the issue of reduced acceleration with each input as the velocity increases?

**Comment by mdcrosby** [comment]
As the agent speeds up the drag on it increases effectively giving it a maximum speed. This is intended as it corresponds with real-world physics where objects cannot accelerate indefinitely by applying the same force (unless ignoring air resistance/friction/etc.).

**Comment by dan9thsense** [comment]
Thanks for the insight.

**Comment by MLanghof** [comment]
@mdcrosby, could you clarify the exact amount of rotation the agent undergoes in one action? Is it 6 degrees or 0.1 radians?

Thanks!

**Comment by beyretb** [comment]
6 degrees for one turn action. 
We'll release a documentation about the physics of the agent and the environment later this week, we're just fully committed to finalising the submission process for today at the moment.

**Comment by MLanghof** [comment]
Hi @beyretb, is the physics documentation already out? You provided some helpful information in https://github.com/beyretb/AnimalAI-Olympics/issues/26#issuecomment-505965980, but with the discussion in #43 it appears there are still some unknowns.

I understand that you're in contact with Unity regarding these things, but it would be very useful to know what can and can't be relied upon (and in which circumstances, especially regarding the `env` settings).

Thanks!

**Comment by beyretb** [comment]
Hi @MLanghof ,

I haven't been able to put together this documentation just yet, running the competition is actually more time consuming than I expected, and I'm also travelling these days. I still have a plan to put one together once I'm back but it will mostly cover the physics parameters of each object (mass, friction, drag) as well as the physics functions used to move the agent (force applied for a single step). But anything else (physics computations, speed, collisions...) will be computed by Unity's physX engine and is out of scope for the documentation of this competition.

Have a look at my response in the other topic about the speed, it is reliable as a model parameter. I would expect that a neural net should be able to learn from this parameter, but there is no obvious formula to get the time used to compute this speed. Therefore it's tricky to infer a distance from it.
