### ISSUE TITLE
Tiny window for rendering

### ISSUE THREAD

**Issue by vakker** [beyretb/AnimalAI-Olympics#40]
Hi

During training the rendering is done in a tiny window (regardless of the `resolution` param).
E.g. running `trainDopamine.py` and `trainMLAgents.py` does not render the top view the same way as `visualizeArena.py` does.
What controls this?
It's hard to see what's happening this way.

Thanks

**Comment by beyretb** [comment]
Hello,

The `resolution` parameter is only for the agent's observations, it will change the default `84x84` to a square of size `resolution x resolution`. It does not impact what you see in the window.

During training you can increase the size of the window by grabbing one of the corner with your mouse (same way you would with any window). Be aware that a bigger window means slower rendering and therefore slower training.

Also keep in mind the window rendering and the agent's observations *are asynchronous**, which makes the image jump quite a bit.

You can also play around with the `inference` parameter of an environment that will slow down the window rendering, it's made for visualising trained agents but will work during training (only with a single agent). You can then press `C` to have a view from the agent's perspective.

**Comment by vakker** [comment]
Gotcha, `inference=True` did the trick.
Thanks!
