### ISSUE TITLE
Orientation in the observations

### ISSUE THREAD

**Issue by vakker** [beyretb/AnimalAI-Olympics#41]
Hi

I was wondering if including the orientation or rotational speed in the observations would be make sense.
Currently it can be inferred from the velocity but when the agent is just rotating in one place there's only the visual information.

Thanks

**Comment by beyretb** [comment]
Hi,

This is actually not feasible as the agent technically doesn't have an angular velocity. When you send a non zero turn action, it rotates the agent by 6 degrees which changes its orientation instantaneously. Your agent will not have any angular momentum either.

**Comment by vakker** [comment]
I see, thanks.
