### ISSUE TITLE
Why numpy>=1.13.3,<=1.14.5?

### ISSUE THREAD

**Issue by ironbar** [beyretb/AnimalAI-Olympics#44]
I have tried using numpy 1.16.1 and it works. Is there a reason for that specific set of versions?

Thanks

**Comment by beyretb** [comment]
Hi, the only reason is that the two packages are based on [ML agents](https://github.com/Unity-Technologies/ml-agents) which at the time used this requirement. I'm not sure if there was a particular reason for that but I see they have extended to `>=1.13.3,<=1.16.1` in the last version. You can of course use the version you want in your submissions.

**Comment by ironbar** [comment]
Great, thanks!
