### ISSUE TITLE
console output

### ISSUE THREAD

**Issue by dan9thsense** [beyretb/AnimalAI-Olympics#47]
Is it possible to get the console output or perhaps some log files from the runs?  That would help a lot with debugging.  The stdout and stderr text files have very little info in them.

**Comment by beyretb** [comment]
Hi,

We cannot give the standard output logs as you are not supposed to extract any information from the evaluation phase. Concerning the standard error logs, you should be able to debug your code through the [testing process](https://github.com/beyretb/AnimalAI-Olympics/blob/master/documentation/submission.md#test-your-docker-image).

If you have no error during this phase but end up with an error at evaluation time and cannot fix it from the curated stderr file, then you can [ask on the EvalAI forum](https://evalai-forum.cloudcv.org/c/animal-ai-olympics-2019) and give us your submission ID (the one you get when pushing your docker image). We will then manually get the logs and send them to you (which might take a bit of time).

**Comment by dan9thsense** [comment]
Sounds good, thanks.
