### ISSUE TITLE
ArenaConfig  (yaml) doesn't load any configuration on Windows

### ISSUE THREAD

**Issue by Bonum** [beyretb/AnimalAI-Olympics#51]
While running directly: AnimalAI-Olympics\env\AnimalAI.exe correctly displays all random objects,
trying to use python api:
AnimalAI-Olympics\examples>python visualizeArena.py configs/5-SpatialReasoning.yaml
displays an empty arena with blue ball which cannot be controlled.
The same is true with other *.yaml files.
Something wrong is going with yaml loader.
I have installed:
pyyaml                 5.1.1              pypi_0    pypi
yaml                      0.1.7             hc54c509_2

I put two print() in arena_config.py ::
class ArenaConfig(yaml.YAMLObject):
    yaml_tag = u'!ArenaConfig'

    def __init__(self, yaml_path=None):
        if yaml_path is not None:
            self.arenas = yaml.load(open(yaml_path, 'r'), Loader=yaml.Loader).arenas
            print("AAA 2 "+yaml_path)
        else:
            print("AAA 3")
            self.arenas = {}
 
Here is the output:
AnimalAI-Olympics\examples>python visualizeArena.py configs/5-SpatialReasoning.yaml
AAA configs/5-SpatialReasoning.yaml
AAA 2 configs/5-SpatialReasoning.yaml
AAA 3

------------------------------
It seems ArenaConfig() is initialized twice and the second time there is no *.yaml parameter?!

**Comment by mdcrosby** [comment]
I cannot recreate this error on the Windows machine I have access to for testing.

Are you using the animalai (or animalai-train) pip package with python 3.6? Both seem to work fine with a fresh install.

Could you ellaborate on what you mean by:
I have installed:
pyyaml 5.1.1 pypi_0 pypi
yaml 0.1.7 hc54c509_2

The pip package only requires pyYAML 5.1.1 so perhaps this is what is causing the issue.

**Comment by Bonum** [comment]
Due to https://github.com/beyretb/AnimalAI-Olympics/issues/32
I used old install_requires for animalai_train setup, but this is not related to the problem.

I reinstalled everything in a new virtual env without animalai_train and yaml 0.1.7 :
conda list
```
# packages in environment at Q:\Anaconda\envs\animalai:
#
# Name                    Version                   Build  Channel
animalai                  1.0.3                    pypi_0    pypi
certifi                   2019.6.16                py36_1    conda-forge
cloudpickle               1.2.1                    pypi_0    pypi
future                    0.17.1                   pypi_0    pypi
grpcio                    1.11.1                   pypi_0    pypi
gym                       0.13.1                   pypi_0    pypi
jsonpickle                1.2                      pypi_0    pypi
numpy                     1.14.5                   pypi_0    pypi
pillow                    5.4.1                    pypi_0    pypi
pip                       19.0.3                   py36_0    conda-forge
protobuf                  3.6.1                    pypi_0    pypi
pyglet                    1.3.2                    pypi_0    pypi
python                    3.6.3                         4    conda-forge
pyyaml                    5.1.1                    pypi_0    pypi
scipy                     1.3.0                    pypi_0    pypi
setuptools                41.0.1                   py36_0    conda-forge
six                       1.12.0                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wheel                     0.33.4                   py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge

```


I even tried with full path-parameter:
`AnimalAI-Olympics\examples>python visualizeArena.py Q:/AI/Contests/NIPS/AnimalAI/AnimalAI-Olympics/examples/configs/1-Food.yaml`

but the problem persists.

**Comment by beyretb** [comment]
Hi,

I don't have a windows machine at hand at the moment so I can only try to help you by asking you to conduct a few steps yourself:

- running `python visualizeArena.py configs/5-SpatialReasoning.yaml` do you get any error message or is the environment just stuck? 
- if you have an error paste it here, if not wait for a few seconds and interrupt the process (ctrl+c) in the terminal and paste the call stack here, this will help identify where the code is stuck
- if you have a unity logfile paste its content here too

My guess is not on the yaml loader, but rather on the communicator between the environment and the API. There seems to be issues on windows with the `grpcio` package...

**Comment by Bonum** [comment]
Hi,
You are right, it shouldn't be yaml loader, since even without *.yaml parameter it behaves in the same way -  empty arena with blue ball which cannot be controlled. Only [c] - change camera view works.

-  the environment is just stuck without any error messages
-  here is the log after Ctl+C (I just added one print to be see the yaml parameter) :

```
Q:\AI\Contests\NIPS\AnimalAI\AnimalAI-Olympics\examples>python visualizeArena.py configs/5-SpatialReasoning.yaml

AAA configs/5-SpatialReasoning.yaml
Traceback (most recent call last):
  File "visualizeArena.py", line 40, in <module>
    env = init_environment(env_path, docker_target_name, no_graphics, worker_id, run_seed)
  File "visualizeArena.py", line 29, in init_environment
    play=True
  File "Q:\Anaconda\envs\animalai\lib\site-packages\animalai\envs\environment.py", line 73, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "Q:\Anaconda\envs\animalai\lib\site-packages\animalai\envs\environment.py", line 504, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "Q:\Anaconda\envs\animalai\lib\site-packages\animalai\envs\rpc_communicator.py", line 77, in initialize
    if not self.unity_to_external.parent_conn.poll(90):
  File "Q:\Anaconda\envs\animalai\lib\multiprocessing\connection.py", line 257, in poll
    return self._poll(timeout)
  File "Q:\Anaconda\envs\animalai\lib\multiprocessing\connection.py", line 330, in _poll
    return bool(wait([self], timeout))
  File "Q:\Anaconda\envs\animalai\lib\multiprocessing\connection.py", line 859, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "Q:\Anaconda\envs\animalai\lib\multiprocessing\connection.py", line 791, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
KeyboardInterrupt
```
It seems that there is no communication with Unity environment.

I used Unity Machine Learning Agents Toolkit (ML-Agents)  some time ago without any problems, but in order to solve current problem I reinstalled Anaconda and everything is lost. It would have been helpful to compare the envs.

**Comment by Bonum** [comment]
Hi, 
The problem is solved!

I had the similar one with ML-Agents. Probably Unity ML messed up with http_proxy settings. The solution may look silly, but it works:

Open  a  new terminal
```
set http_proxy=
set https_proxy= 
```

 That's it. Then running:
 

- python visualizeArena.py configs/5-SpatialReasoning.yaml

 
we have objects and control.

**Comment by beyretb** [comment]
closing the issue as it is solved
