### ISSUE TITLE
Agent not reset between testDocker.py episodes?

### ISSUE THREAD

**Issue by MLanghof** [beyretb/AnimalAI-Olympics#52]
[`testDocker.py`](https://github.com/beyretb/AnimalAI-Olympics/blob/master/examples/submission/test_submission/testDocker.py) runs [5 episodes](https://github.com/beyretb/AnimalAI-Olympics/blob/master/examples/submission/test_submission/testDocker.py#L44) but only [resets the agent once](https://github.com/beyretb/AnimalAI-Olympics/blob/master/examples/submission/test_submission/testDocker.py#L24).

I assume this is just a mistake and not the case for the real submission evaluation script?

**Comment by beyretb** [comment]
correct, that's just a mistake in the test script, in the actual evaluation script we do reset the environment with a new configuration and then call `agent.reset(t)`

I will amend `testDocker.py` when I'm back.

**Comment by giadefa** [comment]
On another matter partially related. In Agent I have no control over the environment. This is done from testDocker.py which is not used in evaluation, so  how would I do it in the real submission to set retro mode for instance?

**Comment by beyretb** [comment]
this has been fixed in v1.0.5
