### ISSUE TITLE
end a run early

### ISSUE THREAD

**Issue by dan9thsense** [beyretb/AnimalAI-Olympics#56]
Is there some way to end a run early?  If we think we have all the food we are going to get, can we tell the run to stop so that we do not continue to lose 1/T reward each step?  This would be equivalent to an animal deciding to go to sleep rather than wander around with predators about.

**Comment by mdcrosby** [comment]
Hi, 

  There is no way to do this. The tests are set up so this is almost never a good thing to do. The thresholds for pass or fail mean that if you've got enough food to pass within the time limit then it will count as a pass no matter how long you take. The vast majority of tasks count success as collecting the food item (usually just one).
