### ISSUE TITLE
Error when running learn.py.

### ISSUE THREAD

**Issue by Lhyejin** [beyretb/AnimalAI-Olympics#58]
There is no argument 'no_graphics' in animalai.env __init__.  What argument does no_graphics match?

![error](https://user-images.githubusercontent.com/28581843/62942808-0e4c1000-be14-11e9-88a2-365dd0325cc9.png)

**Comment by beyretb** [comment]
This was a legacy issue which I just fixed in v1.0.5, you can update via pip or the repo.
