### ISSUE TITLE
Can we use the global view of the environment in training? 

### ISSUE THREAD

**Issue by zbwby819** [beyretb/AnimalAI-Olympics#63]
If yes, how can we get it? 
Thanks!

**Comment by beyretb** [comment]
You can yes, it is not native to the environment but you can use the source code to implement it yourself.

This was discussed [here](https://github.com/beyretb/AnimalAI-Olympics/issues/53#issuecomment-520535798) and the source for the environment is [here](https://github.com/beyretb/AnimalAI-Environment).

**Comment by zbwby819** [comment]
Many thanks!
