### ISSUE TITLE
Get agent x, y, z position during training

### ISSUE THREAD

**Issue by ChWiesner** [beyretb/AnimalAI-Olympics#75]
Is it possible to get an agent's x, y and z position in the environment during training? E.g. to find out an agent's final position after an episode ends.

**Comment by beyretb** [comment]
It is not possible as we want to have a purely vision-based approach.

You can, however, modify the environment yourself and add positions in the set of observations the agent receives. The Unity source is available [here](https://github.com/beyretb/AnimalAI-Environment) (note that we do not support this part of the project at the moment, you can find all the information needed on the [ml-agents repo](https://github.com/Unity-Technologies/ml-agents)). If you participate in the competition keep in mind that you will not have such additional observations.
