### ISSUE TITLE
Question about example config files

### ISSUE THREAD

**Issue by seann999** [beyretb/AnimalAI-Olympics#76]
I'm not sure if this is the place to ask this, but how much do the example config yaml files reflect the actual evaluation environments? I ask this because even an agent with 99.7% success rate in 1-Food.yaml yields only about 20/30 on eval.ai. It's hard to think of any modifications to make it more difficult assuming the environment has no obstacles and one food.

**Comment by seann999** [comment]
Okay, I'm guessing I should read the descriptions of each category more carefully:
"Allowed objects: All goals, Nothing else"
So I guess Category 1 can include moving goals and negative goals (all 4 types).

**Comment by mdcrosby** [comment]
Correct.
