### ISSUE TITLE
Docker and AWS

### ISSUE THREAD

**Issue by dan9thsense** [beyretb/AnimalAI-Olympics#78]
I tried following the [documentation](https://github.com/beyretb/AnimalAI-Olympics/blob/master/documentation/cloudTraining.md) for using AWS with docker.  The AWS instance is a Basic Deep Learning Ubuntu build on a p2.xlarge with 65 GB storage, as specified in the docs.  The dockerfile is the same as I use for submissions for a score.  I almost got it to run, but it has an error:
```
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of Training Brains : 1
INFO:gym_unity:1 agents within environment.
: cannot connect to X server 
```

This is what I used to start the docker image:

```
docker run --runtime=nvidia -v "$PWD"/test_submission:/aaio/test submission_scripts python /aaio/test/testDocker.py
```

**Comment by beyretb** [comment]
I ran your latest submission following the instructions from the documentation and managed to run your command just fine.

Are you using the recommended deep learning AMI? It should work with [this one](https://aws.amazon.com/marketplace/pp/B077GCH38C?ref=cns_srchrow) (you can remove the folders present in the home directory if you're not using them -especially anaconda- as they take a lot of space).

**Comment by dan9thsense** [comment]
That's odd.  I am using the suggested Deep Learning AMI Ubuntu, p2.xlarge, as specified in the documentation:
Deep Learning Base AMI (Ubuntu 16.04) Version 19.2 - ami-0dda3a10b93f38b21

I would need to get more permissions (for 8 vCPUs) to run the instance you linked to.  It seems that the issue is with opening a graphical window (cannot connect to X server).

**Comment by dan9thsense** [comment]
I uploaded the docker image that I submitted and you tested and, sure enough, it runs on the AWS machine.  There must be something wrong with the docker image that I created on the AWS machine.  I'll investigate further.

**Comment by dan9thsense** [comment]
Works fine now.  Never figured it out, just rebuilt the docker image from scratch and it works.

**Comment by beyretb** [comment]
glad you managed to fix the issue!
