### ISSUE TITLE
Gym Wrapper multi-agent

### ISSUE THREAD

**Issue by arin-kwak** [beyretb/AnimalAI-Olympics#79]
Hi. Thank you for holding a good contest.

Do you still have a plan about support for multi-agent in Gym Wrapper?
or Do we have to implement it?

**Comment by beyretb** [comment]
Hi, this is not something we are working on at the moment no, I might look into it later after the competition ends.

**Comment by arin-kwak** [comment]
Ok. Thank you for answering.
