### ISSUE TITLE
Instructions for final submissions

### ISSUE THREAD

**Issue by dan9thsense** [beyretb/AnimalAI-Olympics#82]
Are there instructions for how to make final submissions for consideration?

**Comment by beyretb** [comment]
Yes, we're putting them together today and will send out an email before the end of the day. Adding an extra track to a live competition turned out to be less straightforward than we thought, everything will be good shortly.

**Comment by beyretb** [comment]
Details can be found [here](https://github.com/beyretb/AnimalAI-Olympics/blob/master/documentation/final_submission.md) (and most likely in your inbox).

Let's leave this topic open for any question related to the final submission process.
