### ISSUE TITLE
Env directory is ignored in .gitignore

### ISSUE THREAD

**Issue by Alphamineron** [beyretb/AnimalAI-Olympics#83]
Hey, I don't know if this is supposed to be a public thing but it seems like according to your README.md, you want people to be able to check out your project. In which case, I'd like to point out that your **./env directory is ignored in .gitignore** so nothing inside it is uploaded to GitHub... that includes the **UnityEnvironment executable** that you mention multiple times in your setup/installation documentation, so basically there isn't any executable.

**Comment by beyretb** [comment]
Hello, this is normal yes, as we support several platforms we let users download the correct version for either linux, mac or windows.

Have a look at [the requirements in the readme](https://github.com/beyretb/AnimalAI-Olympics/blob/master/README.md#requirements), it contains links to these three executables.
