### ISSUE TITLE
Question about the way about curriculum

### ISSUE THREAD

**Issue by Gs1997XX** [beyretb/AnimalAI-Olympics#94]
@beyretb Hello, recently our team try to use your env with cite.
We do not find the code to record the trajectory during the agent training？Is there a API to read the agent state and items state while playing the game?

Best wishes

**Comment by beyretb** [comment]
Hello! Appologies for the late response, I was having issues with my github account.

I haven't implemented this feature in the environment but I agree it would be useful! In theory you should be able to do so by following [this notebook](https://github.com/beyretb/AnimalAI-Olympics/blob/master/examples/environment_tutorial.ipynb) and replacing the hard coded moves in cell 18 with a keyboard input inside the stepping loop.

**Comment by mdcrosby** [comment]
v3 (currently in beta here https://github.com/mdcrosby/animal-ai) outputs the agent position as an observation by default. You can use this to reconstruct the trajectory. Automatic output of the trajectory will be in one of the next releases.
