### ISSUE TITLE
Modify environment assets / make new environment?

### ISSUE THREAD

**Issue by FishAres** [beyretb/AnimalAI-Olympics#96]
I know the goal of this project is reproducibility, but the types of tasks I'm trying to do right now need some specific types of textures on e.g. walls/floors. Is there a relatively straight-forward way of replacing textures / adding new object to the supplied environments without having to rebuild an environment from scratch on UnityML? Thanks!

**Comment by mdcrosby** [comment]
Unfortunately not with this version. Colour is easy to vary, but there is no method for changing textures. There is also no way to add new types of object (that aren't just combinations of existing ones) without editing via Unity. 

We are currently working on a new version in which this may be possible (depending on your exact need). No release date yet though. It would be useful to know more about your usecase in case it is something we can easily incorporate as we work on the new version.
